name: chatterbox_tts_flutter
description: A modern Flutter desktop application for ChatterboxTTS with beautiful UI and native audio controls.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP & Backend Communication  
  http: ^1.1.0
  
  # State Management
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true